package format

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"sort"
	"time"

	"github.com/go-pdf/fpdf"

	"github.com/codelake-dev/licscan/internal/scanner"
	"github.com/codelake-dev/licscan/internal/version"
)

// codelakeLogoPNG is the embedded codelake brand logo rendered on the
// CRA evidence PDF cover. Sourced from https://cdn.codelake.dev/logo/codelake_logo.png
// — refresh the file in assets/ to update.
//
//go:embed assets/codelake_logo.png
var codelakeLogoPNG []byte

// logoAspectRatio is the embedded logo's width÷height (1956×422 ≈ 4.635).
// Used to scale the logo at a target height without distortion.
const logoAspectRatio = 1956.0 / 422.0

// CRAPDF renders a regulator-friendly EU CRA Article 13 evidence PDF
// alongside the machine-readable CycloneDX SBOM. White background +
// monospace dep tables + manufacturer cover page.
//
// Layout:
//
//	Page 1   Cover  — title, manufacturer, product, CRA Art. 13 reference,
//	                  scan timestamp, licscan tool attribution
//	Page 2+  Body   — summary table (counts per risk level) + full dep
//	                  table sorted by descending risk
//	Footer   Per-page footer with licscan version + page x/y
func CRAPDF(w io.Writer, result *scanner.Result, manifest CRAManifest) error {
	pdf := fpdf.New("P", "mm", "A4", "")
	// tr maps UTF-8 source strings to the cp1252 encoding the default
	// Helvetica/Courier fonts speak — without it, em-dashes and section
	// signs render as the literal mojibake "â€"" / "Â§".
	tr := pdf.UnicodeTranslatorFromDescriptor("")

	pdf.SetTitle(craReportTitle(manifest), true)
	pdf.SetAuthor("licscan ("+version.Short()+")", true)
	pdf.SetCreator("licscan", true)
	pdf.SetSubject(tr("EU CRA Article 13 — Software Bill of Materials evidence"), true)

	pdf.SetFooterFunc(func() {
		pdf.SetY(-15)
		pdf.SetFont("Helvetica", "I", 8)
		pdf.SetTextColor(120, 120, 120)
		footer := tr(fmt.Sprintf("Generated by licscan %s — Page %d / {nb}",
			version.Short(), pdf.PageNo()))
		pdf.CellFormat(0, 8, footer, "", 0, "C", false, 0, "")
	})
	pdf.AliasNbPages("")

	// Register the embedded brand logo once so every page that wants
	// it can reference the same in-memory image without re-decoding.
	pdf.RegisterImageOptionsReader("codelake-logo",
		fpdf.ImageOptions{ImageType: "PNG", ReadDpi: true},
		bytes.NewReader(codelakeLogoPNG))

	writeCRACover(pdf, result, manifest, tr)
	writeCRASummary(pdf, result, tr)
	writeCRADependencies(pdf, result, tr)

	return pdf.Output(w)
}

func craReportTitle(manifest CRAManifest) string {
	if manifest.Product.Name != "" {
		return "EU CRA Evidence — " + manifest.Product.Name
	}
	return "EU CRA Evidence"
}

// ── Cover page ─────────────────────────────────────────────────

func writeCRACover(pdf *fpdf.Fpdf, result *scanner.Result, manifest CRAManifest, tr func(string) string) {
	pdf.AddPage()

	// Brand logo top-right: 50mm wide, height derived from aspect ratio
	// so the proportions stay correct regardless of the source PNG.
	const logoWidthMM = 50.0
	logoHeightMM := logoWidthMM / logoAspectRatio
	pageWidthMM, _ := pdf.GetPageSize()
	leftMarginMM, topMarginMM, rightMarginMM, _ := pdf.GetMargins()
	logoX := pageWidthMM - rightMarginMM - logoWidthMM
	pdf.ImageOptions("codelake-logo", logoX, topMarginMM, logoWidthMM, logoHeightMM,
		false, fpdf.ImageOptions{ImageType: "PNG"}, 0, "")

	// Reserve enough vertical space for the logo before the title sits
	// next to it on the left.
	pdf.SetXY(leftMarginMM, topMarginMM+logoHeightMM+2)

	pdf.SetFont("Helvetica", "B", 22)
	pdf.SetTextColor(20, 20, 20)
	pdf.CellFormat(0, 14, tr("EU CRA Compliance Evidence"), "", 1, "L", false, 0, "")

	pdf.SetFont("Helvetica", "", 11)
	pdf.SetTextColor(110, 110, 110)
	pdf.CellFormat(0, 7, tr("Regulation (EU) 2024/2847 — Article 13, Annex I §1(2)(s)"), "", 1, "L", false, 0, "")
	pdf.Ln(8)

	pdf.SetDrawColor(220, 220, 220)
	pdf.SetLineWidth(0.3)
	pdf.Line(20, pdf.GetY(), 190, pdf.GetY())
	pdf.Ln(6)

	craLabelValueRow(pdf, tr, "Product", orValue(manifest.Product.Name, basenameOrEmpty(result.ScanPath)))
	if manifest.Product.Version != "" {
		craLabelValueRow(pdf, tr, "Product version", manifest.Product.Version)
	}
	if manifest.Product.Category != "" {
		craLabelValueRow(pdf, tr, "Product category", manifest.Product.Category)
	}
	if manifest.Product.SupportLifecycleEnd != "" {
		craLabelValueRow(pdf, tr, "Support lifecycle end", manifest.Product.SupportLifecycleEnd)
	}
	pdf.Ln(4)

	craSectionTitle(pdf, tr, "Manufacturer")
	if manifest.Manufacturer.IsZero() {
		craGrayNote(pdf, tr, "Manufacturer block was not set in .licscan.yml — submission to a regulator requires Name, Email, URL, Country (Article 13(2)).")
	} else {
		craLabelValueRow(pdf, tr, "Name", manifest.Manufacturer.Name)
		if manifest.Manufacturer.Email != "" {
			craLabelValueRow(pdf, tr, "Email", manifest.Manufacturer.Email)
		}
		if manifest.Manufacturer.URL != "" {
			craLabelValueRow(pdf, tr, "URL", manifest.Manufacturer.URL)
		}
		if manifest.Manufacturer.Country != "" {
			craLabelValueRow(pdf, tr, "Country", manifest.Manufacturer.Country)
		}
	}
	pdf.Ln(4)

	craSectionTitle(pdf, tr, "Scan metadata")
	craLabelValueRow(pdf, tr, "Scan target", result.ScanPath)
	craLabelValueRow(pdf, tr, "Total dependencies", fmt.Sprintf("%d", len(result.Dependencies)))
	detectors := "none"
	if len(result.Detectors) > 0 {
		detectors = joinStrings(result.Detectors, ", ")
	}
	craLabelValueRow(pdf, tr, "Detectors run", detectors)
	craLabelValueRow(pdf, tr, "Generated at", time.Now().UTC().Format(time.RFC3339))
	craLabelValueRow(pdf, tr, "Generated by", "licscan "+version.Short())
	pdf.Ln(8)

	craSectionTitle(pdf, tr, "About this document")
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(60, 60, 60)
	pdf.MultiCell(0, 5.5,
		tr("This document is a Software Bill of Materials (SBOM) prepared as "+
			"evidence supporting the obligations imposed by Regulation (EU) 2024/2847 "+
			"(Cyber Resilience Act), Article 13 and Annex I §1(2)(s). The accompanying "+
			"machine-readable SBOM is provided in CycloneDX 1.5 JSON format alongside this PDF.\n\n"+
			"This document is generated automatically and supports — but does not "+
			"itself constitute — a declaration of conformity. The manufacturer remains "+
			"responsible for verifying that the inventory below is complete and that "+
			"the listed components have been subjected to the vulnerability handling "+
			"and reporting processes required by the Regulation."),
		"", "", false)
}

func craLabelValueRow(pdf *fpdf.Fpdf, tr func(string) string, label, value string) {
	pdf.SetFont("Helvetica", "B", 10)
	pdf.SetTextColor(60, 60, 60)
	pdf.CellFormat(50, 6, tr(label), "", 0, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(20, 20, 20)
	pdf.CellFormat(0, 6, tr(value), "", 1, "L", false, 0, "")
}

func craSectionTitle(pdf *fpdf.Fpdf, tr func(string) string, title string) {
	pdf.SetFont("Helvetica", "B", 12)
	pdf.SetTextColor(40, 40, 40)
	pdf.CellFormat(0, 8, tr(title), "", 1, "L", false, 0, "")
}

func craGrayNote(pdf *fpdf.Fpdf, tr func(string) string, msg string) {
	pdf.SetFont("Helvetica", "I", 10)
	pdf.SetTextColor(150, 100, 30)
	pdf.MultiCell(0, 5.5, tr(msg), "", "", false)
}

// ── Summary page ───────────────────────────────────────────────

func writeCRASummary(pdf *fpdf.Fpdf, result *scanner.Result, tr func(string) string) {
	pdf.AddPage()
	craSectionTitle(pdf, tr, "License risk summary")
	pdf.Ln(2)

	type row struct {
		label   string
		count   int
		r, g, b int
	}
	rows := []row{
		{"Viral / Problematic", result.Summary[scanner.RiskViral.String()], 163, 113, 247},
		{"Strong Copyleft", result.Summary[scanner.RiskStrongCopyleft.String()], 248, 81, 73},
		{"Weak Copyleft", result.Summary[scanner.RiskWeakCopyleft.String()], 210, 153, 34},
		{"Permissive", result.Summary[scanner.RiskPermissive.String()], 63, 185, 80},
		{"Unknown", result.Summary[scanner.RiskUnknown.String()], 110, 118, 129},
	}

	pdf.SetFont("Helvetica", "B", 10)
	pdf.SetFillColor(245, 245, 245)
	pdf.SetTextColor(60, 60, 60)
	pdf.CellFormat(120, 8, tr("Risk level"), "1", 0, "L", true, 0, "")
	pdf.CellFormat(50, 8, tr("Count"), "1", 1, "R", true, 0, "")

	pdf.SetFont("Helvetica", "", 10)
	for _, r := range rows {
		pdf.SetTextColor(r.r, r.g, r.b)
		pdf.CellFormat(120, 7, tr(r.label), "1", 0, "L", false, 0, "")
		pdf.CellFormat(50, 7, fmt.Sprintf("%d", r.count), "1", 1, "R", false, 0, "")
	}

	pdf.SetTextColor(20, 20, 20)
	pdf.SetFont("Helvetica", "B", 10)
	pdf.CellFormat(120, 8, tr("Total"), "1", 0, "L", false, 0, "")
	pdf.CellFormat(50, 8, fmt.Sprintf("%d", len(result.Dependencies)), "1", 1, "R", false, 0, "")
}

// ── Dependency table ───────────────────────────────────────────

func writeCRADependencies(pdf *fpdf.Fpdf, result *scanner.Result, tr func(string) string) {
	pdf.AddPage()
	craSectionTitle(pdf, tr, "Dependency inventory")
	pdf.Ln(2)

	sorted := make([]scanner.Dependency, len(result.Dependencies))
	copy(sorted, result.Dependencies)
	sort.SliceStable(sorted, func(i, j int) bool {
		if sorted[i].PrimaryRisk() != sorted[j].PrimaryRisk() {
			return sorted[i].PrimaryRisk() > sorted[j].PrimaryRisk()
		}
		return sorted[i].Name < sorted[j].Name
	})

	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetFillColor(245, 245, 245)
	pdf.SetTextColor(60, 60, 60)
	pdf.CellFormat(85, 7, tr("Package"), "1", 0, "L", true, 0, "")
	pdf.CellFormat(30, 7, tr("Version"), "1", 0, "L", true, 0, "")
	pdf.CellFormat(30, 7, tr("License"), "1", 0, "L", true, 0, "")
	pdf.CellFormat(25, 7, tr("Risk"), "1", 0, "L", true, 0, "")
	pdf.CellFormat(20, 7, tr("Ecosystem"), "1", 1, "L", true, 0, "")

	pdf.SetFont("Courier", "", 8)
	for _, d := range sorted {
		risk := d.PrimaryRisk()
		r, g, b := riskRGB(risk)
		pdf.SetTextColor(20, 20, 20)
		pdf.CellFormat(85, 6, tr(truncate(d.Name, 42)), "1", 0, "L", false, 0, "")
		pdf.CellFormat(30, 6, tr(truncate(d.Version, 14)), "1", 0, "L", false, 0, "")
		pdf.CellFormat(30, 6, tr(truncate(d.PrimaryLicense(), 14)), "1", 0, "L", false, 0, "")
		pdf.SetTextColor(r, g, b)
		pdf.CellFormat(25, 6, tr(riskShort(risk)), "1", 0, "L", false, 0, "")
		pdf.SetTextColor(20, 20, 20)
		pdf.CellFormat(20, 6, tr(d.Ecosystem), "1", 1, "L", false, 0, "")
	}
}

func riskShort(r scanner.RiskLevel) string {
	switch r {
	case scanner.RiskViral:
		return "Viral"
	case scanner.RiskStrongCopyleft:
		return "Strong"
	case scanner.RiskWeakCopyleft:
		return "Weak"
	case scanner.RiskPermissive:
		return "Permissive"
	default:
		return "Unknown"
	}
}

func riskRGB(r scanner.RiskLevel) (int, int, int) {
	switch r {
	case scanner.RiskPermissive:
		return 63, 185, 80
	case scanner.RiskWeakCopyleft:
		return 210, 153, 34
	case scanner.RiskStrongCopyleft:
		return 248, 81, 73
	case scanner.RiskViral:
		return 163, 113, 247
	default:
		return 110, 118, 129
	}
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n-1] + "…"
}

func joinStrings(parts []string, sep string) string {
	if len(parts) == 0 {
		return ""
	}
	out := parts[0]
	for _, p := range parts[1:] {
		out += sep + p
	}
	return out
}
