package format

import (
	"fmt"
	"io"
	"sort"
	"time"

	"github.com/go-pdf/fpdf"

	"github.com/codelake-dev/licscan/internal/scanner"
	"github.com/codelake-dev/licscan/internal/version"
)

// CRAPDF renders a regulator-friendly EU CRA Article 13 evidence PDF
// alongside the machine-readable CycloneDX SBOM. White background +
// monospace dep tables + manufacturer cover page.
//
// Layout:
//
//	Page 1   Cover  — title, manufacturer, product, CRA Art. 13 reference,
//	                  scan timestamp, licscan tool attribution
//	Page 2+  Body   — summary table (counts per risk level) + full dep
//	                  table sorted by descending risk
//	Footer   Per-page footer with licscan version + page x/y
func CRAPDF(w io.Writer, result *scanner.Result, manifest CRAManifest) error {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetTitle(craReportTitle(manifest), true)
	pdf.SetAuthor("licscan ("+version.Short()+")", true)
	pdf.SetCreator("licscan", true)
	pdf.SetSubject("EU CRA Article 13 — Software Bill of Materials evidence", true)

	pdf.SetFooterFunc(func() {
		pdf.SetY(-15)
		pdf.SetFont("Helvetica", "I", 8)
		pdf.SetTextColor(120, 120, 120)
		footer := fmt.Sprintf("Generated by licscan %s — Page %d / {nb}",
			version.Short(), pdf.PageNo())
		pdf.CellFormat(0, 8, footer, "", 0, "C", false, 0, "")
	})
	pdf.AliasNbPages("")

	writeCRACover(pdf, result, manifest)
	writeCRASummary(pdf, result)
	writeCRADependencies(pdf, result)

	return pdf.Output(w)
}

func craReportTitle(manifest CRAManifest) string {
	if manifest.Product.Name != "" {
		return "EU CRA Evidence — " + manifest.Product.Name
	}
	return "EU CRA Evidence"
}

// ── Cover page ─────────────────────────────────────────────────

func writeCRACover(pdf *fpdf.Fpdf, result *scanner.Result, manifest CRAManifest) {
	pdf.AddPage()

	pdf.SetFont("Helvetica", "B", 22)
	pdf.SetTextColor(20, 20, 20)
	pdf.CellFormat(0, 14, "EU CRA Compliance Evidence", "", 1, "L", false, 0, "")

	pdf.SetFont("Helvetica", "", 11)
	pdf.SetTextColor(110, 110, 110)
	pdf.CellFormat(0, 7, "Regulation (EU) 2024/2847 — Article 13, Annex I §1(2)(s)", "", 1, "L", false, 0, "")
	pdf.Ln(8)

	pdf.SetDrawColor(220, 220, 220)
	pdf.SetLineWidth(0.3)
	pdf.Line(20, pdf.GetY(), 190, pdf.GetY())
	pdf.Ln(6)

	craLabelValueRow(pdf, "Product", orValue(manifest.Product.Name, basenameOrEmpty(result.ScanPath)))
	if manifest.Product.Version != "" {
		craLabelValueRow(pdf, "Product version", manifest.Product.Version)
	}
	if manifest.Product.Category != "" {
		craLabelValueRow(pdf, "Product category", manifest.Product.Category)
	}
	if manifest.Product.SupportLifecycleEnd != "" {
		craLabelValueRow(pdf, "Support lifecycle end", manifest.Product.SupportLifecycleEnd)
	}
	pdf.Ln(4)

	craSectionTitle(pdf, "Manufacturer")
	if manifest.Manufacturer.IsZero() {
		craGrayNote(pdf, "Manufacturer block was not set in .licscan.yml — submission to a regulator requires Name, Email, URL, Country (Article 13(2)).")
	} else {
		craLabelValueRow(pdf, "Name", manifest.Manufacturer.Name)
		if manifest.Manufacturer.Email != "" {
			craLabelValueRow(pdf, "Email", manifest.Manufacturer.Email)
		}
		if manifest.Manufacturer.URL != "" {
			craLabelValueRow(pdf, "URL", manifest.Manufacturer.URL)
		}
		if manifest.Manufacturer.Country != "" {
			craLabelValueRow(pdf, "Country", manifest.Manufacturer.Country)
		}
	}
	pdf.Ln(4)

	craSectionTitle(pdf, "Scan metadata")
	craLabelValueRow(pdf, "Scan target", result.ScanPath)
	craLabelValueRow(pdf, "Total dependencies", fmt.Sprintf("%d", len(result.Dependencies)))
	detectors := "none"
	if len(result.Detectors) > 0 {
		detectors = joinStrings(result.Detectors, ", ")
	}
	craLabelValueRow(pdf, "Detectors run", detectors)
	craLabelValueRow(pdf, "Generated at", time.Now().UTC().Format(time.RFC3339))
	craLabelValueRow(pdf, "Generated by", "licscan "+version.Short())
	pdf.Ln(8)

	craSectionTitle(pdf, "About this document")
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(60, 60, 60)
	pdf.MultiCell(0, 5.5,
		"This document is a Software Bill of Materials (SBOM) prepared as "+
			"evidence supporting the obligations imposed by Regulation (EU) 2024/2847 "+
			"(Cyber Resilience Act), Article 13 and Annex I §1(2)(s). The accompanying "+
			"machine-readable SBOM is provided in CycloneDX 1.5 JSON format alongside this PDF.\n\n"+
			"This document is generated automatically and supports — but does not "+
			"itself constitute — a declaration of conformity. The manufacturer remains "+
			"responsible for verifying that the inventory below is complete and that "+
			"the listed components have been subjected to the vulnerability handling "+
			"and reporting processes required by the Regulation.",
		"", "", false)
}

func craLabelValueRow(pdf *fpdf.Fpdf, label, value string) {
	pdf.SetFont("Helvetica", "B", 10)
	pdf.SetTextColor(60, 60, 60)
	pdf.CellFormat(50, 6, label, "", 0, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(20, 20, 20)
	pdf.CellFormat(0, 6, value, "", 1, "L", false, 0, "")
}

func craSectionTitle(pdf *fpdf.Fpdf, title string) {
	pdf.SetFont("Helvetica", "B", 12)
	pdf.SetTextColor(40, 40, 40)
	pdf.CellFormat(0, 8, title, "", 1, "L", false, 0, "")
}

func craGrayNote(pdf *fpdf.Fpdf, msg string) {
	pdf.SetFont("Helvetica", "I", 10)
	pdf.SetTextColor(150, 100, 30)
	pdf.MultiCell(0, 5.5, msg, "", "", false)
}

// ── Summary page ───────────────────────────────────────────────

func writeCRASummary(pdf *fpdf.Fpdf, result *scanner.Result) {
	pdf.AddPage()
	craSectionTitle(pdf, "License risk summary")
	pdf.Ln(2)

	type row struct {
		label   string
		count   int
		r, g, b int
	}
	rows := []row{
		{"Viral / Problematic", result.Summary[scanner.RiskViral.String()], 163, 113, 247},
		{"Strong Copyleft", result.Summary[scanner.RiskStrongCopyleft.String()], 248, 81, 73},
		{"Weak Copyleft", result.Summary[scanner.RiskWeakCopyleft.String()], 210, 153, 34},
		{"Permissive", result.Summary[scanner.RiskPermissive.String()], 63, 185, 80},
		{"Unknown", result.Summary[scanner.RiskUnknown.String()], 110, 118, 129},
	}

	pdf.SetFont("Helvetica", "B", 10)
	pdf.SetFillColor(245, 245, 245)
	pdf.SetTextColor(60, 60, 60)
	pdf.CellFormat(120, 8, "Risk level", "1", 0, "L", true, 0, "")
	pdf.CellFormat(50, 8, "Count", "1", 1, "R", true, 0, "")

	pdf.SetFont("Helvetica", "", 10)
	for _, r := range rows {
		pdf.SetTextColor(r.r, r.g, r.b)
		pdf.CellFormat(120, 7, r.label, "1", 0, "L", false, 0, "")
		pdf.CellFormat(50, 7, fmt.Sprintf("%d", r.count), "1", 1, "R", false, 0, "")
	}

	pdf.SetTextColor(20, 20, 20)
	pdf.SetFont("Helvetica", "B", 10)
	pdf.CellFormat(120, 8, "Total", "1", 0, "L", false, 0, "")
	pdf.CellFormat(50, 8, fmt.Sprintf("%d", len(result.Dependencies)), "1", 1, "R", false, 0, "")
}

// ── Dependency table ───────────────────────────────────────────

func writeCRADependencies(pdf *fpdf.Fpdf, result *scanner.Result) {
	pdf.AddPage()
	craSectionTitle(pdf, "Dependency inventory")
	pdf.Ln(2)

	sorted := make([]scanner.Dependency, len(result.Dependencies))
	copy(sorted, result.Dependencies)
	sort.SliceStable(sorted, func(i, j int) bool {
		if sorted[i].PrimaryRisk() != sorted[j].PrimaryRisk() {
			return sorted[i].PrimaryRisk() > sorted[j].PrimaryRisk()
		}
		return sorted[i].Name < sorted[j].Name
	})

	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetFillColor(245, 245, 245)
	pdf.SetTextColor(60, 60, 60)
	pdf.CellFormat(85, 7, "Package", "1", 0, "L", true, 0, "")
	pdf.CellFormat(30, 7, "Version", "1", 0, "L", true, 0, "")
	pdf.CellFormat(30, 7, "License", "1", 0, "L", true, 0, "")
	pdf.CellFormat(25, 7, "Risk", "1", 0, "L", true, 0, "")
	pdf.CellFormat(20, 7, "Ecosystem", "1", 1, "L", true, 0, "")

	pdf.SetFont("Courier", "", 8)
	for _, d := range sorted {
		risk := d.PrimaryRisk()
		r, g, b := riskRGB(risk)
		pdf.SetTextColor(20, 20, 20)
		pdf.CellFormat(85, 6, truncate(d.Name, 42), "1", 0, "L", false, 0, "")
		pdf.CellFormat(30, 6, truncate(d.Version, 14), "1", 0, "L", false, 0, "")
		pdf.CellFormat(30, 6, truncate(d.PrimaryLicense(), 14), "1", 0, "L", false, 0, "")
		pdf.SetTextColor(r, g, b)
		pdf.CellFormat(25, 6, riskShort(risk), "1", 0, "L", false, 0, "")
		pdf.SetTextColor(20, 20, 20)
		pdf.CellFormat(20, 6, d.Ecosystem, "1", 1, "L", false, 0, "")
	}
}

func riskShort(r scanner.RiskLevel) string {
	switch r {
	case scanner.RiskViral:
		return "Viral"
	case scanner.RiskStrongCopyleft:
		return "Strong"
	case scanner.RiskWeakCopyleft:
		return "Weak"
	case scanner.RiskPermissive:
		return "Permissive"
	default:
		return "Unknown"
	}
}

func riskRGB(r scanner.RiskLevel) (int, int, int) {
	switch r {
	case scanner.RiskPermissive:
		return 63, 185, 80
	case scanner.RiskWeakCopyleft:
		return 210, 153, 34
	case scanner.RiskStrongCopyleft:
		return 248, 81, 73
	case scanner.RiskViral:
		return 163, 113, 247
	default:
		return 110, 118, 129
	}
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n-1] + "…"
}

func joinStrings(parts []string, sep string) string {
	if len(parts) == 0 {
		return ""
	}
	out := parts[0]
	for _, p := range parts[1:] {
		out += sep + p
	}
	return out
}
