package format

import (
	"fmt"
	"io"
	"sort"
	"strings"
	"time"

	"github.com/codelake-dev/licscan/internal/scanner"
	"github.com/codelake-dev/licscan/internal/version"
)

// Notice renders a NOTICE / THIRD_PARTY_LICENSES file listing every
// dependency with its license. Sorted alphabetically by ecosystem then
// package name. This is the attribution document many open-source
// licenses require you to ship alongside your binary.
func Notice(w io.Writer, result *scanner.Result, projectName string) error {
	if projectName == "" {
		projectName = "This software"
	}

	deps := make([]scanner.Dependency, len(result.Dependencies))
	copy(deps, result.Dependencies)
	sort.Slice(deps, func(i, j int) bool {
		if deps[i].Ecosystem != deps[j].Ecosystem {
			return deps[i].Ecosystem < deps[j].Ecosystem
		}
		return deps[i].Name < deps[j].Name
	})

	header := fmt.Sprintf(`THIRD-PARTY SOFTWARE NOTICES AND INFORMATION

%s includes third-party software components governed by the
licenses listed below. The original copyright notices and license texts
are reproduced below for informational purposes.

Generated by licscan %s on %s.
Total: %d dependencies.

`,
		projectName,
		version.Short(),
		time.Now().UTC().Format("2006-01-02"),
		len(deps),
	)

	if _, err := io.WriteString(w, header); err != nil {
		return err
	}

	if _, err := io.WriteString(w, strings.Repeat("=", 72)+"\n\n"); err != nil {
		return err
	}

	for i, dep := range deps {
		license := dep.PrimaryLicense()
		entry := fmt.Sprintf("%d. %s@%s\n   License: %s\n   Ecosystem: %s\n",
			i+1, dep.Name, dep.Version, license, dep.Ecosystem)

		if dep.Manifest != "" {
			entry += fmt.Sprintf("   Manifest: %s\n", dep.Manifest)
		}

		entry += "\n"

		if _, err := io.WriteString(w, entry); err != nil {
			return err
		}
	}

	if _, err := io.WriteString(w, strings.Repeat("=", 72)+"\n\n"); err != nil {
		return err
	}

	footer := fmt.Sprintf("End of THIRD-PARTY SOFTWARE NOTICES for %s.\n", projectName)
	_, err := io.WriteString(w, footer)
	return err
}
